version: "3.3"
services:
  db:
    container_name: db
    image: postgres:14.3-alpine
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
  backend:
    depends_on:
      - db
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-config log_conf.yml"
    restart: always
    ports:
      - 80:8000
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - APP_SECRET_STRING=${APP_SECRET_STRING}
    networks:
      - app-network
    volumes:
      - .:/code

volumes:
  db-data: {}
networks:
  app-network: