"""Added attribute name in Route

Revision ID: 08d7c8274058
Revises: 4dda4dd9c9d2
Create Date: 2022-11-16 14:11:34.947183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d7c8274058'
down_revision = '4dda4dd9c9d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('name', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'name')
    # ### end Alembic commands ###
