"""reverse name workouttypes-users

Revision ID: 1b0c1d724d8d
Revises: 7c84ff023453
Create Date: 2022-11-04 16:22:58.779363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0c1d724d8d'
down_revision = '7c84ff023453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
