"""Added backref Subscription and Features

Revision ID: 3d31cb1745ed
Revises: 7e5dc3e53ce9
Create Date: 2022-11-11 19:55:28.773753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d31cb1745ed'
down_revision = '7e5dc3e53ce9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
