"""Changed attribute roles in Route

Revision ID: 4dda4dd9c9d2
Revises: f6dc78bcf37b
Create Date: 2022-11-16 13:54:23.204967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dda4dd9c9d2'
down_revision = 'f6dc78bcf37b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
