"""m2m user-workout

Revision ID: 6d0a10a1e01f
Revises: 6a73fe77bfdd
Create Date: 2022-11-10 14:49:31.538576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0a10a1e01f'
down_revision = '6a73fe77bfdd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
