"""Added relationship in subscriptions (Features)

Revision ID: 7e5dc3e53ce9
Revises: 0cda529708e9
Create Date: 2022-11-11 14:49:22.059162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5dc3e53ce9'
down_revision = '0cda529708e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
