"""Added back_populates Subscription and Features

Revision ID: d48929bfcc02
Revises: 3d31cb1745ed
Create Date: 2022-11-11 19:59:27.774987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48929bfcc02'
down_revision = '3d31cb1745ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
