"""Add back_populates

Revision ID: f6b32d2fe266
Revises: 6d0a10a1e01f
Create Date: 2022-11-10 14:53:16.455333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b32d2fe266'
down_revision = '6d0a10a1e01f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
