"""Added table Route

Revision ID: f6dc78bcf37b
Revises: d48929bfcc02
Create Date: 2022-11-16 13:38:04.310745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dc78bcf37b'
down_revision = 'd48929bfcc02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_has_role',
    sa.Column('Route_id', sa.Integer(), nullable=False),
    sa.Column('Role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['Route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('Route_id', 'Role_id')
    )
    op.create_index(op.f('ix_route_has_role_Role_id'), 'route_has_role', ['Role_id'], unique=False)
    op.create_index(op.f('ix_route_has_role_Route_id'), 'route_has_role', ['Route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_has_role_Route_id'), table_name='route_has_role')
    op.drop_index(op.f('ix_route_has_role_Role_id'), table_name='route_has_role')
    op.drop_table('route_has_role')
    op.drop_table('route')
    # ### end Alembic commands ###
