"""Change patronymic

Revision ID: fa0271b2afe5
Revises: 9675c3457633
Create Date: 2022-10-20 15:50:19.210479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0271b2afe5'
down_revision = '9675c3457633'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patronymic', sa.String(length=45), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=45), nullable=False))
    op.drop_constraint('user_phonenumber_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['phone'])
    op.drop_column('user', 'patronomic')
    op.drop_column('user', 'phonenumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phonenumber', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('patronomic', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_phonenumber_key', 'user', ['phonenumber'])
    op.drop_column('user', 'phone')
    op.drop_column('user', 'patronymic')
    # ### end Alembic commands ###
